### ISSUE TITLE
[Bug] enrolment_created event not working

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-logstore_xapi#121]
v2.0.0
Reported by @nikidev:

> The enrolment_created event seems to be not working. I made a comparison in the code between the old version and version 2.0.0 and it's the same. I double checked in the settings if the event is enabled but it is enabled by default. So this is not the problem.

**Comment by Dasuntha** [comment]
Error is is  'Agent` must have exactly one identifier not `0` in `statement.context.instructor. We need to fix this in ' lib/emitter/src/Events/EnrolmentCreated.php'.

**Comment by nikidev** [comment]
Great job @Dasuntha   !  :)

**Comment by ryasmi** [comment]
Wow yeah good work @Dasuntha 👍

**Comment by nikidev** [comment]
By the way @Dasuntha,  in the same context   do you have an idea  for that  issue: https://github.com/xAPI-vle/moodle-logstore_xapi/issues/129

 The Quiz completed  event is not emitting by the emitter.    I guess the problem is in /lib/emitter/src/Events/AttemptCompleted.php  

But I don't know  where exactly  it is. 
Everything  seems to be fine.  :)

**Comment by davidpesce** [comment]
Looks like this was fixed in v2.2.2 with PR #152
