### ISSUE TITLE
Link problem in README.md step 1. download the plugin

### ISSUE THREAD

**Issue by ivanoterouvigo** [davidpesce/moodle-logstore_xapi#154]
**Link problem in README.md step 1. download the plugin**
- {{I am trying to download this plugins but it says, https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/xapi.zip?raw=true}}

Could you update this link, please.

**Comment by ryasmi** [comment]
Hey @ivanoterouvigo, good spot. This is a bit of a tricky link to update because the latest zip file is not directly accessible, you'd have to actually update this link on every release to point to the new file. We can however change the text and use the [latest release URL](https://github.com/xAPI-vle/moodle-logstore_xapi/releases/latest) to provide access to a download.

**Comment by ryasmi** [comment]
Should be okay now 👍
