### ISSUE TITLE
Assignment Graded statement doesn't send

### ISSUE THREAD

**Issue by eljowers** [davidpesce/moodle-logstore_xapi#173]
**Description**
- When I go in as a teacher and grade something, the plugin doesn't send a statement to my LRS. 

**Version**
- Release version 2.2.4, Version #: 2018022201

**Steps to reproduce the bug**
1. Create quiz with questions that must be graded by the teacher.
2. Take quiz as a student.
3. Grade quiz as a teacher.

**Expected behaviour**
- I assume this action should send a statement with the "graded" verb to my LRS, but it does not. Let me know if this is not the intended behavior.

**Actual behaviour**
- Sends viewed and reviewed statements, but nothing about being graded or completed. It also does not send a submitted statement when the student submits the quiz.

**Client information**
- OS: Ubuntu 16.04
- Browser: Firefox 60.0.1
- Moodle: 3.4

**Comment by davidpesce** [comment]
Thanks for reporting this, @eljowers! We've been working on a rewrite of the plugin and I believe this is on the list of statements getting rewritten. I'm going to leave this open as a reminder to verify it in the new version.

**Comment by eljowers** [comment]
Sooo, if I needed this working yesterday, how could I go about fixing that? I need to have graded working and add a few more events, but I don't understand how this plugin works and interfaces with Moodle well enough to get it working myself. Is there a previous version or branch somewhere where this works? The verbs I've found to not work so far are graded, completed, and submitted.

**Comment by davidpesce** [comment]
I think the issue lies more in the version of Moodle. Moodle changed how they handle things for certain events. It's at that point that some of these stopped working.

We are still working on the new version, but if you're feeling adventurous and have a test instance of Moodle to try it out on, take a look at the master branch. I have not done this just yet, so proceed with extreme caution.

Otherwise, you'll have to dig into the transformer code for the particular events that aren't working.

**Comment by eljowers** [comment]
I do have a version of Moodle to play with. Do you know which version of Moodle the plugin last worked with?

**Comment by vbhayden** [comment]
By your release dates, the current version of the plugin `v2.2.4` was released after Moodle 3.4 had been released and while 3.1 and 3.2 were still receiving official support.  

Since 2.2.4 was classified as a Release while those versions of moodle were around, is the issue that Moodle somewhat-recently made retroactive changes to those older versions that prevent this plugin's releases from working?

**Comment by vbhayden** [comment]
Is there a high-level list of work that needs to be done for the plugin to resume its functionality?  My team has no problem doing the work and submitting a PR, but we aren't familiar with the changes Moodle made to its event propagation or the structure of Log plugins.

**Comment by caperneoignis** [comment]
You wouldn't happen to be using randomized questions? This might be related to #174

**Comment by vbhayden** [comment]
We were having issues with a variety of statements, eventually abandoning the plugin and writing our own listener to send statements by monitoring Moodle's database.

**Comment by caperneoignis** [comment]
Gotcha, not a problem, I just noticed something similar myself and will attempt to fix it.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
