### ISSUE TITLE
Timestamps on answers

### ISSUE THREAD

**Issue by petarnikolovski** [davidpesce/moodle-logstore_xapi#292]
Hi all, I noticed that when logstore xAPI sends quizzes and answers statements to my Learning Locker, that timestamps of answers are all same as the timestamp on the related quiz (as if all the questions were answered at the same time when the quiz completion event was emitted). Does this plugin supports, or is planing on supporting unique timestamp for each answer? I.e is it possible that the timestamp of the answer statement corresponds to the actual time the user answered a question, rather than to time of the quiz submission? Is this even possible to have with moodle?

**Comment by ryasmi** [comment]
Hi @petarGitNik, unfortunately it's not possible to use the time at which each question was actually answered in Moodle at the moment using the Logstore because Moodle doesn't actually store the answers until the quiz is submitted, hence we have to log the time of submission rather than the time the questions were answered.

**Comment by petarnikolovski** [comment]
@ryansmith94 Thank you for the answer, I was afraid that it was the Moodles "fault".
