### ISSUE TITLE
Not sending any statements

### ISSUE THREAD

**Issue by FlorianTolk** [davidpesce/moodle-logstore_xapi#293]
**Description**
- After configuring and enabling Logstore xAPI to point to [https://lrs.adlnet.gov/xAPI/](https://lrs.adlnet.gov/xAPI/) no statements end up being pushed to the LRS

**Version**
- plugin release 3.8.1
- Moodle branch 35_stable
- Ubuntu 16.04

**Steps to reproduce the bug**
1. [Setup Moodle](https://docs.moodle.org/35/en/Step-by-step_Installation_Guide_for_Ubuntu)
2. Add the plugin via uploading the zip from the admin GUI
3. Configure your plugin with user credentials, and to point to [https://lrs.adlnet.gov/xAPI/](https://lrs.adlnet.gov/xAPI/)
4. Enable the plugin from your admin console
5. Take a test/logout/view a module/log in new user/etc.

**Expected behavior**
- Should send statement(s) to LRS

**Actual behavior**
- No observable response from plugin, no visible statements on LRS

**Server information**
- Postgres Database with BasicAuth.

**Client information**
- OS: Ubuntu 16.04
- Browser: Firefox for Ubuntu v 62.0.3 (64-bit)

**Additional information**
- Database is open and free to the public to view so recreating the issue should be easy. Can create an account at [https://lrs.adlnet.gov/register](https://lrs.adlnet.gov/register).
- Can find LRS source code on [Github](https://github.com/adlnet/ADL_LRS).

**Comment by ryasmi** [comment]
Hi @FlorianTolk, thanks for reporting your issue and following our format. Could you please perform the following checks?

- Check your LRS endpoint in the plugin settings ends with "/xAPI".
- Check that you have not set your LRS username and password in the plugin settings to your login username and password for the LRS rather than your API basic auth username (key) and basic auth password (secret).
- Check that you have the cron configured for your Moodle instance, if you've enabled/disabled the "background mode" plugin setting.
- Check that your Moodle server has access to your LRS.

**Comment by FlorianTolk** [comment]
Hi @ryansmith94
unchecking `Send statements by scheduled task?` did fix the issue. Thanks!

**Comment by ryasmi** [comment]
No worries 👍 note that not sending them by scheduled task will mean that page loads wait until statements have been sent which is why it's turned on by default.
