### ISSUE TITLE
sending H5P events

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#412]
My understanding of H5P in Moodle is as follows:

> H5P is sending xAPI statements from the JS client and its various sub widgets to the Moodle server, those xAPI statements are saved inside a special db table, and not on the main Moodle mdl_logstore_standard_log where all the potential events that can be sent via the moodle-logstore_xapi
are saved.

I see two options for getting those statements sent to the LRS:

1. An entirely independent plugin that runs a cron task to send the statements.
2. An additional cron task in this plugin, or step within the existing emit_task. 

My initial reaction was option 1, but the more I think about it option 2 seems preferable since many users of this plugin will not also use H5P. 

Anybody want to weigh in to support or refute either option?

**Comment by caperneoignis** [comment]
@garemoko From what I remember of H5P is the only part of that program that actually interacts with LRS is feedback submission. Otherwise nothing get sent to the LRS. 

Now on to your point, I would say 2, because no one wants to track down the additional plugin to add with h5p to fix something h5p should have added in the first place. So I think the event piece would be the best, and either make it truly work with the LRS or add additional events to the xapi_logstore plugin. that listens for the event triggers from hp5.

**Comment by davidpesce** [comment]
With the context of H5P being brought into Moodle core and Moodle HQ working on their own implementation of xAPI for H5P (https://tracker.moodle.org/browse/MDL-67734), I think we can safely close this one.

The HQ approach seems to be Moodle functioning as an xAPI forwarder via built-in Moodle web services. Take a look at the 'H5P for Moodle 3.9' epic: https://tracker.moodle.org/browse/MDL-67425
