### ISSUE TITLE
Event filter

### ISSUE THREAD

**Issue by CinecaElearning** [davidpesce/moodle-logstore_xapi#54]
**Motive**
A lot of events are now sent to the LRS; Moodle admins could decide which are interesting and which can be discarded.

**Result**
A menu of the events that can be sent in the plugin settings.

**Additional information**
A possible implementation is developed in our branch xapi_store_2016031401. Events that are available to be sent are taken from the translator routes and presented in the settings.php. A setting for the guest generated events is present too. When the event is to be sent, the __construct parses the setting and the is_event_ignored decides if the event is to be sent or not.

**Comment by ryasmi** [comment]
Hey if you have a branch that does this already feel free to make a PR and we'll take a look. I don't know if @jlowe64 or @garemoko have any input on this.

**Comment by CinecaElearning** [comment]
Thanks! I had the opportunity to talk about this via email with @jlowe64, which kindly explained to me how to propose our code (I'm fairly new to github). I'll make a PR but first I want to open other issues that our code already covers. I hadn't had the time to open them yesterday.

**Comment by jlowe64** [comment]
@CinecaElearning I would suggest making a PR so we can see the code. 

I've had, I think, one other group request this sort of thing and I think some folks may be into the idea of filtering just interesting stuff to the LRS. For my organization specifically, we actually prefer having more information rather than less, and the number of events being sent over has been mitigated by batching.

I think if we integrate it, the default setting should be that _all_ events are passed through, and that only in the case of a filter should it start filtering. We should also be mindful of performance issues with checks, as specifically for people with large numbers of users, performance is a priority.

**Comment by CinecaElearning** [comment]
@jlowe64 I created the PR. If I recall correctly, by now, the code needs the admin to specify the events that are to be sent. Changing the default to send all is not a problem though.

**Comment by garemoko** [comment]
Yeh +1 to this as a feature. I'd want all events on by default though.

**Comment by timothyjoh** [comment]
+1 to this, would make it much better for us

**Comment by davidpesce** [comment]
@CinecaElearning going through old issues and attempting to get the status of them. Any chance you were able to create this PR? If not, would you be able to forward the email from @jlowe64 explaining what needs to be done in the PR to davidpesce@gmail.com?

**Comment by davidpesce** [comment]
This is complete as of v1.5.0
