### ISSUE TITLE
Totara program 'enrolled to' statement

### ISSUE THREAD

**Issue by isheeler** [davidpesce/moodle-logstore_xapi#571]
**Description**
We are using the plugin on a Totara installation. Totara has a 'program' feature that groups courses together. Learners who enrol on one course are enrolled in all courses within that program. It would be great if the plugin could send statements to report when someone enrolled on a program so that we can keep a count of unique learners on a program. 

**Version**
3.0

**Steps to reproduce the bug**
It's Totara specific. No way to send a statement of enrolment on a program. At the moment we can only report when someone enrols on a course within that program, and this leads to people being counted multiple times.

**Expected behaviour**
Learner enrolled to [programe name]  

**Actual behaviour**
None

**Comment by BrendanHalley** [comment]
This brings up an interesting point about whether Totara events are going to be included in this plugin or this project forked.

I've been meaning to add all the unique Totara events to this plugin for a while.

**Comment by davidpesce** [comment]
I think it may be confusing for users to have totara-specific admin settings. There are already enough events in the list that I'm thinking it needs to be a searchable/filtered.

That being said, rather than forking for a new plugin, why not a separate branch on this repo?

**Comment by BrendanHalley** [comment]
Seperate branch would work fine. I work for a Totara partner and I'm happy to maintain the branch.

I'll get an issue up with the proposed way forward for this plugin and Totara.

**Comment by ryasmi** [comment]
I agree with David that "it may be confusing for users to have totara-specific admin settings". I also agree that the events list might need to be searchable (that one is probably a separate issue).

I think I would prefer that the project wasn't forked, I would also prefer that we didn't have a separate branch. I think I would prefer to have a moodle folder and a totara folder, but I think that might complicate installation and our CI process because I think certain files are expected in certain folders. Therefore, whilst the separate branch is not ideal, I think it's probably the way we'll have to go.

**Comment by garemoko** [comment]
Coming at this from another angle, this could be seen as just an example of a more general problem that the Moodle site might not have events that this plugin tracks. In addition to the Totora case, other cases might include:

- We add tracking for an event associated with an non-core plugin
- An event is removed in a later version of Moodle 
- A Moodle site which uninstalls some core modules that are not required in order to simplify the Moodle.

I wonder if it's possible for us to detect which events are registered on the current Moodle site and only display settings for those events. See https://github.com/moodle/moodle/blob/6153be6850869cdc3a6ae925dcf6e688ac481333/report/eventlist/classes/list_generator.php#L52

**Comment by ryasmi** [comment]
That's a good point, thanks @garemoko. I had assumed we couldn't dynamically change that list in the settings, but if we can do that and detect what events are available, then we should totally do that instead.

**Comment by BrendanHalley** [comment]
Good idea @garemoko.

I've just checked Totara and this class and function still exist with continued backwards compatibility support. I expect it's not going away or if it does a replacement will be offered.

This would give a lot of flexibility with what can be in the main branch without causing issues or confusion once the plugin is installed. I think this removes all issues I had with having Totara and other events in master.

**Comment by BrendanHalley** [comment]
@garemoko is the above pull request what you were thinking?

**Comment by ryasmi** [comment]
That looks pretty cool @BrendanHalley :+1:

**Comment by BrendanHalley** [comment]
I've just updated my pull request. It now contains a statement for the event `\totara_program\event\program_assigned` that resolves this issue.

**Comment by garemoko** [comment]
@BrendanHalley yes, that's exactly the sort of thing I had in mind! Nice work!

**Comment by ryasmi** [comment]
Resolved by #583
