### ISSUE TITLE
New log expander examples are wrong

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-logstore_xapi#74]
All the new log expander examples are totally wrong. It looks like they have been generated from the test repository data rather than from a real Moodle database. I propose we roll them all back to the previous version. I haven't checked the translator or emitter examples. 

@jlowe64

**Comment by jlowe64** [comment]
Hmmm, the autogeneration uses the phpunit tests and test repo to generate a statement. So should we manually maintain this, or make the repository correct?

**Comment by garemoko** [comment]
@jlowe64 ideally, we'd totally re-write how the test repository works and make it closer to what Moodle returns, with objects returned actually matching the structure and typical contents of the Moodle database. On the one hand, that's a bunch of work, on the other it'll solve this (and other) issues and the longer we leave it, the more work it is. 

I'm not planning to take this on myself, but I'd certainly cheer you on if you wanted to!

**Comment by jlowe64** [comment]
I think if you can deal with the docs being a bit iffy for a bit, it would be much better to rewrite the test repo. I was thinking that the only major issue we've been having with the test repo is the nested statements for things like questions/answer/feedback. The rest seems okay-ish?

Also, I'm unsure of exactly when the docs got messed up because I did use this on the last release as well, and I would hate to have to hack open the git repo to cherrypick files. 

If we can get this last bit of work done for a proper release by end of June + Scorm data, I can come back to this after.

**Comment by garemoko** [comment]
The biggest problem from my POV is that the readStoreRecord and readStoreRecords methods return exactly the same object and properties regardless of which Moodle table they are simulating. It would be better if we actually replicated complete Moodle tables and routed those read methods to the correct data based on what was requested.

**Comment by jlowe64** [comment]
Yeah, that's exactly what I was thinking as well. It'd be a big job, I think, but would make things a lot nicer in the end. Like you said, longer we wait, the bigger the job. And to be honest, I think it's better to fix the test repo anyway, because sometimes it gets a bit tedious to maintain the docs when they could just be generated. It could also aid in debugging better, as well.

**Comment by ryasmi** [comment]
I think the docs are auto-generated when you run the tests now right @jlowe64?

**Comment by garemoko** [comment]
@ryansmith94 read above - they are auto generated incorrectly for the expander.

**Comment by jlowe64** [comment]
Yes they are auto generate while tuning tests using the test repository.

**Comment by ryasmi** [comment]
Ah right I see the issue now. We'd have to potentially override all of the methods or come up with some way of changing the implementation of readStoreRecord and readStoreRecords so that it generates something more realistic.

**Comment by garemoko** [comment]
"come up with some way of changing the implementation of readStoreRecord and readStoreRecords so that it generates something more realistic" would be my preference. If we override too much we're not testing anything.

**Comment by ryasmi** [comment]
Version 3 has new examples so closing this in preparation for the release.

**Comment by ryasmi** [comment]
https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v3.0.0
