### ISSUE TITLE
Due date on assessments should be iso format

### ISSUE THREAD

**Issue by gmoger-jisc** [davidpesce/moodle-logstore_xapi#779]
**Description**
Due dates captured against assessments are in unix timestamp format and not converted to ISO 8601 as is standard across xAPI specification.  Here is an example:

`            "object": {
                "id": "https://DOMAIN/mod/assign/view.php?id=1661199",
                "definition": {
                    "type": "http://adlnet.gov/expapi/activities/assessment",
                    "name": {
                        "en": "Portfolio Task 1 Submission Upload"
                    },
                    "extensions": {
                        "http://xapi.jisc.ac.uk/dueDate": "1598223600"
                    }
                },
                "objectType": "Activity"
            }`

**Version**
- {{master-jisc}} at {{latest}}

**Comment by davidpesce** [comment]
This appears to only impact the jisc version of the plugin and is due to this here: https://github.com/xAPI-vle/moodle-logstore_xapi/blob/544715dc4bcdd1f138ed0aa4c92954d64dbf21fb/src/transformer/utils/get_activity/course_assignment.php#L56

I'm hesitant to change anything with the jisc version as I have no way to test it.
