### ISSUE TITLE
Poor plugin performance

### ISSUE THREAD

**Issue by lanauri** [davidpesce/moodle-logstore_xapi#78]
Hello, 
we are going to use the plugin to send to LRS all the activity of our Campus. Our Campus has enough activity to collect around 3000 entries in 5 minutes during some periodes of the day.

During the test phase we found that we could'nt configure the plugin to send more than 300 records every 5 minutes. We saw that the plugin waits 60 seconds between every "maxbatchsize".
Is this normal behavior? 
How can we configure the plugin so that it can reach up to 3000 records or more every 5 minutes?
Is it possible to avoid this 60 seconds between deliveries?
Thanks, 
noèlia

**Comment by garemoko** [comment]
Do you have the plugin configured to send statements as a scheduled task via cron? How often do you have the cron configured to run? What happens if you increase the maximum batch size to 3000?

**Comment by jlowe64** [comment]
@lanauri this behavior was introduced because there's some organisations doing far more than that number per minute, and we've found it's far better server performance sending in batches. The reason it sends every 60 seconds is because you've set your moodle cron to run every 60 seconds, this is default behavior and is unavoidable in moodle.

The reason you are getting only 300 records is because on the settings page for this plugin, the default behavior is 30 records per minute. So you will need to increase this number on the settings page to get more. 

The settings page is located at: admin settings > plugins > logging > xapi

**Comment by jlowe64** [comment]
@garemoko oops I think we cross posted.

**Comment by lanauri** [comment]
@garemoko, @jlowe64,

we have the Moodle cron set to be executed every 5 minutes.
We changed the 'maxbatchsize' parameter in settings > plugins > logging > xapi from 30 to 300 and we receive 300 registers when the cron is executed and then it waits 60 secs until it sends other 300 registers.
If we increase the 'maxbatchsize' parameter to 3000, LRS doesn't receive anything.

**Comment by jlowe64** [comment]
That may be because your cron is stalling before the next one runs, you may be running out of resources, or any number of things. Have you tried changing the cron to be every 60 seconds and the batches to be lower, like 600?

There will need to be a fair bit of play, but basically you need to find a balance that works.

**Comment by lanauri** [comment]
If the problem was on the resources of the LRS, what configuration shoud we use to increase the performance of the LRS?  Split the LRS and the MongoDB in two servers?  Is there any documentation related with the infraestructure needed in big environments?

**Comment by jlowe64** [comment]
It's very, very difficult to determine the right amount of resources to apply to Moodle. It's a bit of a beast anyway, and it's different for everyone. In my experience, I wouldn't run Moodle on less than 2gb of ram without a database on that node. If you also have a database on the same server, then that number would increase exponentially depending on how large your site is.

For all servers you're using, maybe consider using New Relic to determine the status of your server as it's processing this cronjob. It helped me determine some pesky bottlenecks.

Honestly, the best bet is to increase the frequency of the cron and lower the number of statements. The plugin will work through any backlog until it's done with the surge. Unless you're looking for 100% live data, there's no real need to have that many statements going in within that amount of time. If you are looking for live data, I would seriously consider increasing the resources available to moodle, the database, and the LRS.

**Comment by garemoko** [comment]
Looking at the code in `classes/log/store.php`, the batch size represents how many statements are sent in each batch, but each run of the cron _should_ keep sending batches until all the statements are sent. 

Since your cron is set to 5 minutes but you get batches every 60 seconds, I'm guessing that 60 seconds is how long all the processing takes to generate the statements on the Moodle side, get a response back from the LRS and start generating the next batch. 

Probably this could be made faster if Moodle didn't wait for a response from the LRS before starting to build the next batch of statements, but how much faster depends on how much of that 60 seconds is waiting for the LRS and how much is querying the Moodle database and building the statements. Doing that is also going to put more strain on your Moodle with a potential impact on users. 

Is there any reason why you can't let the events build up a little during busy periods and catch up when it's quieter, so long as you're not averaging more than 5 statements a second in a given day? 

Slightly off topic, another potential problem is that if there's an error and the code stops sending batches for some reason, the events have already been removed from the `logstore_xapi_log` table. IMHO we need more robust batching within `classes/task/emit_task.php` itself.

**Comment by lanauri** [comment]
Hi, 
I did some changes in the LRS infrastructure and nowadays I think that the problem is in the LRS itself instead of on the plugin. So I opened this issue [Poor LRS performance](https://github.com/LearningLocker/learninglocker/issues/836) in the [Learninglocker site](https://github.com/LearningLocker/learninglocker/issues) and I close this one.
Thank-you,
noèlia

**Comment by ht2** [comment]
@lanauri As explained in the referenced ticket, this is most likely a resource/architecture issue where server tuning should be looked at as well as resource scaling (if appropriate) on the LRS side according to the required load being placed.
