### ISSUE TITLE
Quiz completion event is not being pushed

### ISSUE THREAD

**Issue by JoepBakker** [davidpesce/moodle-logstore_xapi#781]
**Description**
- The quiz completed event is being ignored. No statement is pushed on that event.

**Steps to reproduce the bug**
1. Install plugin
2. Enable quiz completed
3. Complete a quiz: all intermediate events will have been pushed, but not completion

**Server information**
- Data is stored in a LearningLocker database using the xApi interface

**Client information**
- OS: Windows (both XAMPP and docker installation)
- Browser: Chrome

**Comment by davidpesce** [comment]
I can confirm this is the case, but the reason is interesting. Moodle itself isn't emitting an event for quiz_submitted. I'm going to confirm with MoodleHQ, but this may not be something we can resolve with this plugin.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/3988068/193929701-07336bb0-b696-450c-ae58-557687f1fc2e.png">

**Comment by davidpesce** [comment]
Did a bit more digging on this and it looks like you may have run into the same issue that I did. When taking a quiz as an admin/teacher, the attempt_submitted event is not fired. When taking it as a student the event (and resulting statement) is sent correctly.
