### ISSUE TITLE
Question - can the plugin be scheduled to run each night?

### ISSUE THREAD

**Issue by KenBurch** [davidpesce/moodle-logstore_xapi#798]
**Description**
- {{Brief description of your bug}}

**Version**
- {{branch}} at {{commit}} on {{version - found in your copy of the VERSION file}} 

**Steps to reproduce the bug**
1. {{steps}}

**Expected behaviour**
- {{feature}} should be {{expectedResult}} because {{reason}}.

**Actual behaviour**
- {{feature}} is {{actualResult}}.

**Server information**
- {{database}} with {{authentication}}.

**Client information**
- OS: {{operatingSystem}}
- Browser: {{browser}} {{version}}

**Additional information**
- {{additionalInfo}})

**Comment by KenBurch** [comment]
Sorry I know GIT isn't the correct place for questions, but there doesn't seem to be any activity on the Moodle plugins page

**Comment by stephen-oh** [comment]
Hi @KenBurch 

Any scheduled task can be changed when logged into the site as an admin. See this article here:
https://docs.moodle.org/36/en/Scheduled_tasks

At the moment the plugin is set to run its scheduled task `emit_task` every minute. Depending on how much activity your site has and the performance of your server this might actually be necessary in order to process the queue of events without creating a backlog. Another setting which will play into this will be the batch size, if the task is running less frequently you will most likely need to increase this.

If you are however wanting to run this at night then I would suggest running it every minute for a good couple of hours at least and monitor how effective that is. You don't want to be in a situation where the task cannot complete the previous days events.

This doc here might we worth a read as it covers adding historical events into the queue which is similar to what you will be doing:
https://github.com/xAPI-vle/moodle-logstore_xapi/blob/master/docs/historical-events.md
